### ISSUE TITLE
I'd like to use this in my monorepo. What should I know?

### ISSUE THREAD

**Issue by jaredpalmer** [adeira/shipit#1]

**Comment by michalsanger** [comment]
Hi Jared, it's cool that you like Shipit! Maybe start a discussion in our monorepo if you have any questions:
https://github.com/adeira/universe/discussions 

What should you know? Well it works fine for us:
https://github.com/adeira/universe/blob/master/.github/workflows/shipit.yml

It could be useful for you to look at the configs of projects we're exporting with this tool:
https://github.com/adeira/universe/tree/master/src/monorepo-shipit/config

**Comment by mrtnzlml** [comment]
Thanks @jaredpalmer for your interest. I'd like to add one more note to @michalsanger comment. Shipit is currently not very reusable because nobody showed interest yet (until now). But I am thinking about making it reusable for a long time (which technically means only moving away our configs and exporting it via NPM for example). This would be a great opportunity to do so.

Would you please let us know whether you are interested in this effort and you'd help us to report any issues with it? I have some capacity to do the necessary changes to Shipit to fit your use-case.
